---
title: "Algorytm Gaussa Newtona"
author: "Dawid Skowroński"
date: "`r Sys.Date()`"
output:
  pdf_document:
    number_sections: true
    dev: cairo_pdf
  html_document:
    df_print: paged
header-includes:
- \usepackage[OT4]{polski}
- \usepackage[utf8]{inputenc}
- \usepackage{graphicx}
- \usepackage{float}
- \usepackage{amsmath}
- \usepackage{rotating}
- \usepackage{bbm}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{float}
- \usepackage{graphicx}
- \renewcommand{\contentsname}{Spis treści}
- \renewcommand{\listfigurename}{Spis wykresów i rysunków}
- \renewcommand{\listtablename}{Spis tabel}
- \renewcommand{\figurename}{Wykres}
- \renewcommand{\tablename}{Tabela}
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 4,
  out.extra='',
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  cache=FALSE,
  dev.args = list(png = list(type = "cairo")))

knitr::opts_chunk$set(
  fig.pos = "H",
  out.extra = "",
  fig.align = "center",
  dev = "pdf",
  dev.args = list(encoding="CP1257.enc")
)

set.seed(282241)

```

```{r, echo=TRUE}
library(ggplot2)
library(MASS)


# Parametry
n <- 10
x <- (1:10)/2
b1 <- 10
b2 <- 3
b3 <- 2
beta <- c(b1,b2,b3)
sig <- 1/2

set.seed(2137)
y_gen <- (b1*x)/(b2+x)+b3 + rnorm(10,mean = 0, sd = sig)


fun_g <- function(x,beta){
  return((beta[1] * x) / (beta[2] + x) + beta[3])
}

grad_g <- function(x, beta){
  return(c(x/(beta[2]+x), - (beta[1] *x)/(beta[2]+x)^2,1))
}

grad_g(1/2, beta= beta)

# Wzór na g(x,beta)

# Definiujemy macierz G

mac_G <- function(wek_x, beta){
  n <- length(wek_x)
  p <- length(beta)
  mac <- matrix(nrow = n, ncol = p)
  for (i in 1:n){
    mac[i, ] <- grad_g(wek_x[i], beta = beta)
  }
  return(mac)
}
```


```{r, echo = TRUE}
# Algorytm Gaussa Newtona
G_N <- function(x,y, beta_0 = c(8,2,1), eps=0.0001 , M=100){
  
  n <- length(x)
  p <- length(beta_0)
  
  stare_beta <- beta_0
  
  y_prog0 <- fun_g(x, beta_0)
  SSR <- sum((y-y_prog0)^2)
  
  # Krok zerowy
  historia <- data.frame()
  
  for (i in 1:M){
    
    y_prog <- fun_g(x, stare_beta)
    G <- mac_G(x, beta = stare_beta)
    
    SSR <- sum((y-y_prog)^2)
    krok <- ginv(t(G) %*% G) %*% t(G)%*%(y-y_prog)

    nowe_beta <- stare_beta + krok
    
    historia <- rbind(
      historia,
      data.frame(
        krok = i-1,
        beta1 = stare_beta[1],
        beta2 = stare_beta[2],
        beta3 = stare_beta[3],
        sigma_kw = SSR / (n - p)
      )
    )
    
    # Warunek stopu
    if (sqrt(sum((nowe_beta-stare_beta)^2))<eps){
      break
    }
    stare_beta <- nowe_beta
  }
  
  y_prog <- fun_g(x, nowe_beta)
  G <- mac_G(x, beta = nowe_beta)
  
  SSR <- sum((y-y_prog)^2)
  
  historia <- rbind(
    historia,
    data.frame(
      krok = i,
      beta1 = nowe_beta[1],
      beta2 = nowe_beta[2],
      beta3 = nowe_beta[3],
      sigma_kw = SSR / (n - p)
    )
  )
  
  return(return(historia))
}

G_N(x,y_gen)
```

